[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line tool to analyze, convert and manipulate colors"
homepage = "https://github.com/sharkdp/pastel"
license = "MIT/Apache-2.0"
name = "pastel"
readme = "README.md"
repository = "https://github.com/sharkdp/pastel"
version = "0.1.0"
edition = "2018"

[dependencies]
# library dependencies
lazy_static = "1.3.0"

# binary-only dependencies (see https://github.com/rust-lang/cargo/issues/1982)
regex = "1"
ansi_term = "0.9"
atty = "0.2"

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help"]

[[bin]]
name = "pastel"
path = "src/cli/main.rs"

[dev-dependencies]
approx = "0.3"
